services:
  - name: whisper-api
    type: web
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10
    autoDeploy: true